version: "3.9"

networks:
  media-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

x-dns: &default-dns
  dns:
    - 172.18.0.10   # Pi-hole static IP

services:

  # -------------------- PIHOLE --------------------
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_PASSWORD}
    volumes:
      - ./config/pihole/etc-pihole:/etc/pihole
      - ./config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80"
    restart: unless-stopped
    networks:
      media-network:
        ipv4_address: 172.18.0.10


  # -------------------- HOMEPAGE --------------------
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.4.182:3000,192.168.4.182:5000
    ports:
      - "3000:3000"
    volumes:
      - ./config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    restart: unless-stopped
    networks:
      - media-network
    <<: *default-dns


  # -------------------- SAMBA --------------------
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - TZ=${TZ}
      - USER=pi;${DB_PASSWORD}
    volumes:
      - ./data:/home/pi/media-stack/data
    ports:
      - "139:139"
      - "445:445"
    command: >
      -s "HomeServer;/home/pi/media-stack/data;yes;no;no;pi;pi;pi"
      -u "pi;${DB_PASSWORD}"
    restart: unless-stopped
    networks:
      - media-network
    <<: *default-dns


  # -------------------- AUDIOBOOKSHELF --------------------
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - "1337:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data/media/audiobooks:/audiobooks
      - ./data/media/podcasts:/podcasts
      - ./config/audiobookshelf:/config
      - ./config/audiobookshelf/metadata:/metadata
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - media-network
    <<: *default-dns


  # -------------------- POSTGRES --------------------
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: audiobookshelf
    volumes:
      - ./config/postgres:/var/lib/postgresql/data
      - ./config/postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - media-network
    <<: *default-dns


  # -------------------- QBITTORRENT --------------------
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - ./data/downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    networks:
      - media-network
    <<: *default-dns


  # -------------------- SONARR --------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/sonarr:/config
      - ./data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
    depends_on:
      - qbittorrent
    networks:
      - media-network
    <<: *default-dns

  # -------------------- PROWLARR --------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - media-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    <<: *default-dns

