networks:
  media-network:
    driver: bridge

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: 192.168.4.182:3000,192.168.4.182:5000
    ports:
      - 3000:3000
    volumes:
      - ./config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - media-network

  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - TZ=${TZ}
      - USER=pi;${DB_PASSWORD}
    volumes:
      - ./data:/home/pi/media-stack/data
    ports:
      - "139:139"
      - "445:445"
    command: -s "HomeServer;/home/pi/media-stack/data;yes;no;no;pi;pi;pi" -u "pi;${DB_PASSWORD}"
    restart: unless-stopped
    networks:
      - media-network

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 1337:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./data/media/audiobooks:/audiobooks
      - ./data/media/podcasts:/podcasts
      - ./config/audiobookshelf:/config
      - ./config/audiobookshelf/metadata:/metadata
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - media-network

  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    volumes:
      - ./data/media/books:/books
      - ./data/media/comics:/comics
      - ./config/kavita:/kavita/config
    environment:
      - TZ=${TZ}
    ports:
      - 5000:5000
    restart: unless-stopped
    networks:
      - media-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: audiobookshelf
    volumes:
      - ./config/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - media-network
